name: Build Next.js App

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your code

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the Node.js version

      - name: Install dependencies
        run: npm ci # Or yarn install / pnpm install

      - name: Build Next.js application
        run: npm run build # Or yarn build / pnpm build

      - name: Commit .next directory
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Build: Commit .next directory"
          file_pattern: ".next/"
          repository: .
